### ISSUE TITLE
Need to integrate more containers

### ISSUE THREAD

**Issue by tyson-swetnam** [genophenoenvo/docker#2]
Need to add Dockerfiles for JupyterLab that @MagicMilly is using with TerraRef Data.

@tyson-swetnam can set up the continuous integrations with DockerHub and CyVerse.

**Comment by MagicMilly** [comment]
@tyson-swetnam, I used a public tool for the current WIP app and did not modify the Dockerfile. Are you referring to the CyVerse Dockerfiles on GitHub you've shown me before? This is the tool I used:
<img width="995" alt="tool_used_for_wip_app" src="https://user-images.githubusercontent.com/34486154/75702748-4cefcd80-5c73-11ea-819c-e4e8717d2da1.png">

**Comment by rbartelme** [comment]
@MagicMilly I think @tyson-swetnam meant that anything explicitly new should go here. Like ML stuff, my Julia project, etc.

**Comment by MagicMilly** [comment]
This issue has moved on to be addressed in multiple, more recent tickets such as [#93](https://github.com/genophenoenvo/terraref-datasets/issues/93) in the terraref-datasets repo.
