### ISSUE TITLE
Fix Julia package installs in Rstudio instance

### ISSUE THREAD

**Issue by rbartelme** [genophenoenvo/docker#9]
Issues with Docker image and Julia+R interoperability. The Julia package installs are failing to load once inside the container.

- [ ] Successfully load Julia packages in Julia CLI environment
- [ ] Invoke Julia packages from inside Rstudio
- [ ] File new issue for beta testing PhyloNetworks with test data on CyVerse

**Comment by dlebauer** [comment]
is this issue still relevant to current work - can it be closed or moved to icebox?

**Comment by rbartelme** [comment]
@dlebauer This can get moved to the icebox. It's an interesting problem, since not much Julia has been implemented at CyVerse, but it's non-essential.
